### ISSUE TITLE
Backend //TODO

### ISSUE THREAD

**Issue by Paulinhx** [hope2handteam/HopetoHand#4]

**Comment by Paulinhx** [comment]
- [ ] 1. Contact Form submit 
- [ ]     Post user data contact  -  Carlos - Wais- Felix
     
- [x] 2. LOGIN-SIGNUP - auth0 - userdata storage - Carlos
- [ ] 3.  Google auth0 
- [ ] 4. post profile picture  - props with image populating cards - Carlos - Wais 
- [ ] 5 . populate accomodation cards with data image - text in geoloc cards  Wais - Carlos - Gman
